services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelwork-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    command: --max_allowed_packet=64M
    container_name: travelwork-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-travelwork}
      MYSQL_USER: ${DB_USERNAME:-travelwork}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: travelwork-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  mysql_data:
